whew
Pancakeo/spacedew_finale pull request #7
Opened 2017-07-17 22:29 UTC by jvinal

2017-07-17 22:32 UTC, jvinal commented
@Pancakeo @TheGauntt

2017-07-17 22:32 UTC, legauntt requested changes

2017-07-17 22:32 UTC, TheGauntt commented on client/html/pages/tom_clancy.html
> +	<audio autoplay="autoplay" loop="loop"><source src="wup.mp3" type="audio/mpeg"/></audio>
File doesn't exist in build - Was this tested?

2017-07-17 22:32 UTC, TheGauntt commented on client/html/pages/tom_clancy.html
> +	<audio autoplay="autoplay" loop="loop"><source src="wup.mp3" type="audio/mpeg"/></audio>
Also, please run "npm run prod" (from client/) and commit resulting dist/

2017-07-17 22:34 UTC, jvinal commented on client/html/pages/tom_clancy.html
> +	<audio autoplay="autoplay" loop="loop"><source src="wup.mp3" type="audio/mpeg"/></audio>
The file is uploaded as part of the pull request.

2017-07-17 22:57 UTC, legauntt requested changes

2017-07-17 22:57 UTC, TheGauntt commented on client/dist/html/pages/tom_clancy.html
> +	<audio autoplay="autoplay" loop="loop"><source src="wup.mp3" type="audio/mpeg"/></audio>
Don't modify dist/, let the build script do that.

2017-07-17 23:04 UTC, jvinal commented on client/dist/html/pages/tom_clancy.html
> +	<audio autoplay="autoplay" loop="loop"><source src="wup.mp3" type="audio/mpeg"/></audio>
That wasn't me; the only thing the build script did to dist/ was apply the exact changes that were in client/html/pages.

2017-07-18 00:10 UTC, TheGauntt commented on client/dist/html/pages/tom_clancy.html
> +	<audio autoplay="autoplay" loop="loop"><source src="wup.mp3" type="audio/mpeg"/></audio>
I see - there's no JS/CSS file so it keeps the hashes the same. This is a great improvement - the only problem is, it doesn't work.

👎

2017-07-18 00:12 UTC, TheGauntt commented
You'll want to use either the public/ folder, or resolve the mp3 correctly. Please test all changes prior to submitting a PR. 💯

2017-07-22 20:06 UTC, merged